### ISSUE TITLE
invalid hwnd

### ISSUE THREAD

**Issue by postredaction** [xoxor4d/iw3xo-radiant#20]
Expression:
    invalid hwnd

Module:    K:\games\mw1\bin\IW3xRadiant.exe
File:    C:\trees\cod3-pc\cod3-modtools\cod3src\src\gfx_d3d\r_init.cpp
Line:    2127

i dont even have that folder on my pc

**Comment by rednose2077** [comment]
That problem is not caused by iw3xo .
The folder is not on your pc because you only have the compiled files of the Modtools. The error is likely a bug of the original Modtools (and that path is within the source code). For these kind of errors there are sometimes workarounds. They can also happen because limits were hit or you did something in an unusual way in the editor.

**Comment by xoxor4d** [comment]
The answer of rednose explains it pretty well. That assert is an original cod4 radiant assert meant for developers with access to the original source code.

I have had quite a few people with that exact assert in the past and almost all of them had the same "issue". 
They did not have the cod4 modtools installed before installing this radiant modification. So please make sure that you have installed them. If you still get that assert after doing so, check if you can open and use the original radiant that comes with the modtools.

**Comment by xoxor4d** [comment]
I guess this is no longer an issue. I might edit that assert to include a small "install" tutorial
