### ISSUE TITLE
[bug] Layers on/off

### ISSUE THREAD

**Issue by Iswenzz** [xoxor4d/iw3xo-radiant#24]
When i toggle off the parent of a layer and then turn it on again it doesn't toggle on the childrens

![image](https://user-images.githubusercontent.com/26555415/219964749-402e7fe3-97ed-46f1-ae8e-2d0c492d1da2.png)

**Comment by xoxor4d** [comment]
Thats definitely something that needs to be done

**Comment by xoxor4d** [comment]
After re-thinking about it, I'll leave that logic like it is because it allows you to quickly disable all child layers to then only turn on the child's you wants to see. You can use the right-click context menu to reset the parent layer and all of its child's. The context menu previously only worked when right clicking the layer name. The committed changes make it work on the hide and freeze buttons as well.
